
package com.ofss.fc.cz.app.creditcard.service;

import javax.xml.ws.WebFault;
import com.oracle.ofss.obp.cz.status.ServiceStatus;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "serviceStatus", targetNamespace = "http://www.oracle.com/ofss/obp/cz/status/")
public class CreateCreditCardfaultMessage
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ServiceStatus faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public CreateCreditCardfaultMessage(String message, ServiceStatus faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public CreateCreditCardfaultMessage(String message, ServiceStatus faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.oracle.ofss.obp.cz.status.ServiceStatus
     */
    public ServiceStatus getFaultInfo() {
        return faultInfo;
    }

}
