
package com.ofss.fc.cz.app.creditcard.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "createCreditCardAccount", targetNamespace = "http://service.creditcard.app.cz.fc.ofss.com", wsdlLocation = "file:/C:/Users/sumathe/Desktop/CreditCardFulfilment/wsdl/CreditCard.wsdl")
public class CreateCreditCardAccount
    extends Service
{

    private final static URL CREATECREDITCARDACCOUNT_WSDL_LOCATION;
    private final static WebServiceException CREATECREDITCARDACCOUNT_EXCEPTION;
    private final static QName CREATECREDITCARDACCOUNT_QNAME = new QName("http://service.creditcard.app.cz.fc.ofss.com", "createCreditCardAccount");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/sumathe/Desktop/CreditCardFulfilment/wsdl/CreditCard.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CREATECREDITCARDACCOUNT_WSDL_LOCATION = url;
        CREATECREDITCARDACCOUNT_EXCEPTION = e;
    }

    public CreateCreditCardAccount() {
        super(__getWsdlLocation(), CREATECREDITCARDACCOUNT_QNAME);
    }

    public CreateCreditCardAccount(WebServiceFeature... features) {
        super(__getWsdlLocation(), CREATECREDITCARDACCOUNT_QNAME, features);
    }

    public CreateCreditCardAccount(URL wsdlLocation) {
        super(wsdlLocation, CREATECREDITCARDACCOUNT_QNAME);
    }

    public CreateCreditCardAccount(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CREATECREDITCARDACCOUNT_QNAME, features);
    }

    public CreateCreditCardAccount(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CreateCreditCardAccount(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CreditCardFulfilmentPtt
     */
    @WebEndpoint(name = "CreditCardFulfilment_pttSoapHttp")
    public CreditCardFulfilmentPtt getCreditCardFulfilmentPttSoapHttp() {
        return super.getPort(new QName("http://service.creditcard.app.cz.fc.ofss.com", "CreditCardFulfilment_pttSoapHttp"), CreditCardFulfilmentPtt.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CreditCardFulfilmentPtt
     */
    @WebEndpoint(name = "CreditCardFulfilment_pttSoapHttp")
    public CreditCardFulfilmentPtt getCreditCardFulfilmentPttSoapHttp(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.creditcard.app.cz.fc.ofss.com", "CreditCardFulfilment_pttSoapHttp"), CreditCardFulfilmentPtt.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CREATECREDITCARDACCOUNT_EXCEPTION!= null) {
            throw CREATECREDITCARDACCOUNT_EXCEPTION;
        }
        return CREATECREDITCARDACCOUNT_WSDL_LOCATION;
    }

}
